reworking services

diff --git a/services/vanpi-core-api/Dockerfile b/services/vanpi-core-api/Dockerfile
--- a/services/vanpi-core-api/Dockerfile
+++ b/services/vanpi-core-api/Dockerfile
@@ -1,32 +1,111 @@
-# reference argument - omitted defaults to latest
-ARG DOCKERHUB_TAG=latest
+ARG ARCH=linux/arm64/v8
+ARG NODE_VERSION=21
+ARG OS=bookworm
+ARG BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")"
+ARG NODE_RED_VERSION=3.1.3
+ARG TAG_SUFFIX=default
 
-# Download base image
-FROM coconup/node-red-docker-debian
+#### Stage BASE ########################################################################################################
+FROM --platform=${ARCH} node:${NODE_VERSION}-${OS} AS base
 
-# reference argument - omitted defaults to null
-ARG EXTRA_PACKAGES
-ENV EXTRA_PACKAGES=${EXTRA_PACKAGES}
+# Copy scripts
+COPY scripts/*.sh /tmp/
 
-# default user is node-red - need to be root to install packages
-USER root
+# Install tools, create Node-RED app and data dir, add user and set rights
+RUN set -ex && \
+    apt-get update && apt-get install -y \
+        bash \
+        tzdata \
+        curl \
+        nano \
+        wget \
+        git \
+        openssl \
+        openssh-client \
+        ca-certificates && \
+    mkdir -p /usr/src/node-red /data && \
+    deluser --remove-home node && \
+    # adduser --home /usr/src/node-red --disabled-password --no-create-home node-red --uid 1000 && \
+    useradd --home-dir /usr/src/node-red --uid 1000 node-red && \
+    chown -R node-red:root /data && chmod -R g+rwX /data && \
+    chown -R node-red:root /usr/src/node-red && chmod -R g+rwX /usr/src/node-red
+    # chown -R node-red:node-red /data && \
+    # chown -R node-red:node-red /usr/src/node-red
 
-# install packages
-RUN apt update && apt upgrade -y && apt install -y python3-pip ${EXTRA_PACKAGES}
+# Set work directory
+WORKDIR /usr/src/node-red
+
+# Setup SSH known_hosts file
+COPY known_hosts.sh .
+RUN ./known_hosts.sh /etc/ssh/ssh_known_hosts && rm /usr/src/node-red/known_hosts.sh
+RUN echo "PubkeyAcceptedKeyTypes +ssh-rsa" >> /etc/ssh/ssh_config
+
+# package.json contains Node-RED NPM module and node dependencies
+COPY package.json .
+COPY flows.json /data
+COPY scripts/entrypoint.sh .
+
+#### Stage BUILD #######################################################################################################
+FROM base AS build
+
+# Install Build tools
+RUN apt-get update && apt-get install -y build-essential python3-pip && \
+    npm install --unsafe-perm --no-update-notifier --no-fund --only=production && \
+    npm uninstall node-red-node-gpio && \
+    cp -R node_modules prod_node_modules
+
+#### Stage RELEASE #####################################################################################################
+FROM base AS RELEASE
+ARG BUILD_DATE
+ARG BUILD_VERSION
+ARG BUILD_REF
+ARG NODE_RED_VERSION
+ARG ARCH
+ARG TAG_SUFFIX=default
+
+LABEL org.label-schema.build-date=${BUILD_DATE} \
+    org.label-schema.docker.dockerfile=".docker/Dockerfile.debian" \
+    org.label-schema.license="Apache-2.0" \
+    org.label-schema.name="Node-RED" \
+    org.label-schema.version=${BUILD_VERSION} \
+    org.label-schema.description="Low-code programming for event-driven applications." \
+    org.label-schema.url="https://nodered.org" \
+    org.label-schema.vcs-ref=${BUILD_REF} \
+    org.label-schema.vcs-type="Git" \
+    org.label-schema.vcs-url="https://github.com/node-red/node-red-docker" \
+    org.label-schema.arch=${ARCH} \
+    authors="Dave Conway-Jones, Nick O'Leary, James Thomas, Raymond Mouthaan"
+
+COPY --from=build /usr/src/node-red/prod_node_modules ./node_modules
+
+# Chown, install devtools & Clean up
+RUN chown -R node-red:root /usr/src/node-red && \
+    apt-get update && apt-get install -y build-essential python3-dev python3 python3-pip pipx bluez usbutils && \
+    rm -r /tmp/*
+
+RUN npm config set cache /data/.npm --global
+
+RUN rm /usr/lib/python3.11/EXTERNALLY-MANAGED
 RUN pip3 install argparse pexpect
+
+USER node-red
+
+# Env variables
+ENV NODE_RED_VERSION=$NODE_RED_VERSION \
+    NODE_PATH=/usr/src/node-red/node_modules:/data/node_modules \
+    PATH=/usr/src/node-red/node_modules/.bin:${PATH} \
+    FLOWS=flows.json
+
+# ENV NODE_RED_ENABLE_SAFE_MODE=true    # Uncomment to enable safe start mode (flows not running)
+# ENV NODE_RED_ENABLE_PROJECTS=true     # Uncomment to enable projects option
+
+# Expose the listening port of node-red
+EXPOSE 1880
+
+# Add a healthcheck (default every 30 secs)
+# HEALTHCHECK CMD curl http://localhost:1880/ || exit 1
 
 # switch back to default user
 USER node-red
 
-# variable not needed inside running container
-ENV EXTRA_PACKAGES=
-
-# add-on nodes follow
-
-RUN cd /usr/src/node-red && npm install --save  node-red-configurable-ping
-RUN cd /usr/src/node-red && npm install --save  node-red-contrib-boolean-logic
-RUN cd /usr/src/node-red && npm install --save  node-red-contrib-influxdb
-RUN cd /usr/src/node-red && npm install --save  node-red-dashboard
-RUN cd /usr/src/node-red && npm install --save  node-red-node-pi-gpiod
-RUN cd /usr/src/node-red && npm install --save  node-red-node-rbe
-
+ENTRYPOINT ["./entrypoint.sh"]
